name: amazon
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.21
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  page_transition: ^2.1.0
  cloud_firestore: ^5.0.2
  persistent_bottom_nav_bar_v2: ^4.0.2
  uuid: ^4.2.1
  image_picker: ^1.0.4
  firebase_storage: ^12.1.0
  flutter_rating_bar: ^4.0.1
  razorpay_flutter: ^1.3.5
  motion_toast: ^2.6.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  assets:
       - assets/images/
       - assets/images/categories/
       - assets/images/carousel_slideshow/
       - assets/images/todays_deals/
       - assets/images/offersNsponcered/
       - assets/images/menu_pics/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
